name: CI Web Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          playwright install

      - name: Run web tests
        run: |
          source venv/bin/activate
          pytest tests/web --html=reports/report.html --self-contained-html

      - name: Upload HTML Report
        if: success() && always()
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: reports/report.html